import Gallery from './components/gallery';

export default function Home() {
  return (
    <>
    <article className="prose">
      <h1>Next App Lab</h1>
      <p>Generated by create next app</p>
    </article>
    <Gallery/>
    </>
  );
}
